### ISSUE TITLE
Creation of a Backend Interface for Wiggle Files Parsing

### ISSUE THREAD

**Issue by mwittep** [Integrative-Transcriptomics/tss-prediction-comparison#13]
## Description

In this user story, you should get familiarized with the interaction with Wiggle files in the language that the prediction is going to be based on. 

## Acceptance

Please describe what is necessary for this ticket to count as resolved. You do not need to repeat the definition-of-done that your team has agreed on generally.

- [x] #23
- [x] #24
- [x] #25
- [x] #26
- [x] Gather this information into the wiki 
- [x] #27

## Definition of Ready

If this issues has been discussed with the team and everybody agrees that it is implementable within one iteration, you can assign the label `ready` to it.

**Comment by Julian-Borbeck** [comment]
Review: 

- Readability: The code is very well structured, and easy to understand
- Functionality: Code passes unit tests with 99% coverage
- Error Handling: Error handling is largely outsourced to external libraries
- Dependencies: New dependencies are Wiggelen and Pandas 
- Style and Formatting: Style is consistent with style guidelines, code is formatted to be readable. 
- Performance: Wiggle file parsing seems to be slow for large files. I am unsure if this can be improved as the parsing is handled by an external library. Suggestion for issue: Review file parsing performance bottleneck
- Code Comments: Very well commented code, every function has a docstring
I like the way the code is structured. It might need reviewing regarding performance
