### ISSUE TITLE
Summarizing the Wrap-Up Phase

### ISSUE THREAD

**Issue by mwittep** [Integrative-Transcriptomics/tss-prediction-comparison#17]
## Description

In order to have clear information on the background knowledge of the project, you will need to summarize the information that we have discussed in the previous weeks.

## Acceptance

Create a creative Wiki-Entry for the following topics, for example by including figures. 

- [x] #18
- [x] #19
- [x] #20

## Definition of Ready

If this issues has been discussed with the team and everybody agrees that it is implementable within one iteration, you can assign the label `ready` to it.

**Comment by AronWichtner** [comment]
reviewed #18 and #20
