### ISSUE TITLE
Transcription and Gene Structure, with Figure

### ISSUE THREAD

**Issue by mwittep** [Integrative-Transcriptomics/tss-prediction-comparison#18]

**Comment by Julian-Borbeck** [comment]
Added first draft of Wikipage with [4b1c9ca](https://github.com/Integrative-Transcriptomics/tss-prediction-comparison/wiki/Prokaryotic-gene-structure-and-transcription/4b1c9ca0c5a76e765e6e9edf00b87f4d9fccebf0)
