### ISSUE TITLE
From the Wiggle files uploaded in the client sides, save them.

### ISSUE THREAD

**Issue by mwittep** [Integrative-Transcriptomics/tss-prediction-comparison#23]
## Description

As developed in #16, the files sent to the API should be kept in memory  or saved in a temp folder for further processing.  

Contract can be found at #37 

## Acceptance

Revise the DONE definitons. 

## Definition of Ready

If this issues has been discussed with the team and everybody agrees that it is implementable within one iteration, you can assign the label `ready` to it.

**Comment by Julian-Borbeck** [comment]
Resolved as part of #14
