### ISSUE TITLE
Do simple math operations on wiggle files

### ISSUE THREAD

**Issue by mwittep** [Integrative-Transcriptomics/tss-prediction-comparison#24]
## Description

From the files handled in #23, find the optimal way of doing math operations on them. This could be either own implementation or python-based libraries. 
 
## Acceptance

Please describe what is necessary for this ticket to count as resolved. You do not need to repeat the definition-of-done that your team has agreed on generally.

- [x] Simple functions are created that receive (a) wiggle file(s) and output simple math operations. 
- [x] Document the usage and goal of the functions. 

## Definition of Ready

If this issues has been discussed with the team and everybody agrees that it is implementable within one iteration, you can assign the label `ready` to it.

**Comment by AronWichtner** [comment]
resolved by #14
