### ISSUE TITLE
Develop functions that summarize the data

### ISSUE THREAD

**Issue by mwittep** [Integrative-Transcriptomics/tss-prediction-comparison#27]
## Description

From #25 and #26, implement the functions that will be the input for #2. 

## Acceptance

_Remember the definition of DONE_

- [x] Implement a function that summarizes multiple technical replicates to be used for a prediction. 
- [x] Implement a function that provides the input for the prediction of TSSs and accounts for possible multiple conditions. 
 
## Definition of Ready

If this issues has been discussed with the team and everybody agrees that it is implementable within one iteration, you can assign the label `ready` to it.

**Comment by Julian-Borbeck** [comment]
Added functionality to prepare the input for TSS prediction. Doesnt account for multiple conditions yet, because those will be handled as seperate jobs
