### ISSUE TITLE
Visualiza the data resulting from the comparisons

### ISSUE THREAD

**Issue by mwittep** [Integrative-Transcriptomics/tss-prediction-comparison#31]
## Description

Based on your reasearch on #30, implement the visualizations. 
## Acceptance

- [x] The desired visualizations are implemented.
- [x] The code has been merged into the main branch

## Definition of Ready

If this issues has been discussed with the team and everybody agrees that it is implementable within one iteration, you can assign the label `ready` to it.

**Comment by habicht12** [comment]
Done!
Code has been merged into main branch on 31.08.2024
