### ISSUE TITLE
First development branch integration

### ISSUE THREAD

**Issue by mwittep** [Integrative-Transcriptomics/tss-prediction-comparison#36]
## Description

Before continuing with the individual branches separated from back-end and front-end, we need a branch that joins both of them before merging gets more complicated. This development branch should then be the base of further branches.

## Acceptance

Please describe what is necessary for this ticket to count as resolved. You do not need to repeat the definition-of-done that your team has agreed on generally.

- [x] The code of both main branches is available in the branch
- [x] No merge conflicts
- [x] The app (backend and frontend servers) is started using one command only.

**Comment by mwittep** [comment]
There is a way of starting vite and flask all just via vite. I recommend looking at TSSpredators Web Package.json (https://github.com/Integrative-Transcriptomics/TSSpredator-GUI/blob/main/package.json), the scripts "server" and "start" provide a similar call as the ones used here. This can be combined into a function tsspredictor, jsut as in tsspredator it is combined as tsspredator.

**Comment by Julian-Borbeck** [comment]
Done. The server can be launched using npm-run-all using yarn.
After the installation of the required backend and frontend packages, the server can be started with yarn start

**Comment by Julian-Borbeck** [comment]
Documented how to setup and run server https://github.com/Integrative-Transcriptomics/tss-prediction-comparison/wiki/How-to-set-up-the-server-on-your-device
