### ISSUE TITLE
Including the annotation of the genome in the evaluation of the results 

### ISSUE THREAD

**Issue by mwittep** [Integrative-Transcriptomics/tss-prediction-comparison#38]
## Description

If a user does not have a MasterTable from TSSpredator, they would still like to know some information on the predicted TSSs. For example, how is the classification with respect to genes, how close are the TSS to the next gene, etc. For this, the user could be able to upload a GFF file to include this information in the analysis. 

Priority: Lower than MasterTable parsing. 

## Acceptance

Please describe what is necessary for this ticket to count as resolved. You do not need to repeat the definition-of-done that your team has agreed on generally.

- [x] #39
- [x] #40
- [x] #41

## Definition of Ready

If this issues has been discussed with the team and everybody agrees that it is implementable within one iteration, you can assign the label `ready` to it.

**Comment by AmelieFl** [comment]
solved on branch 28-parsing-MasterTable. 

- GFF parsing #39 : in file app/GFFParser.py. The parsed data frame only contains the entries of type gene.
- classifying the TSS #40 : in file app/GFFclassifier.py. The predicted TSS are classified according to the wiki entry TSS classification. The output is a data frame which also contains the confidence value of the prediction, the gene name corresponding to the classification, and the distance to the next directed gene. This should also solve #41

**Comment by AronWichtner** [comment]
Reviewed together with Issue #29
