### ISSUE TITLE
Parse the GFF file using available libraries or an own parser

### ISSUE THREAD

**Issue by mwittep** [Integrative-Transcriptomics/tss-prediction-comparison#39]
You can focus on the CDS annotations or gene, since they are the most common ones.

**Comment by AronWichtner** [comment]
Review:

I reviewed the file GFFParser.py on Branch 28-parsing-MasterTable

Readability: readable code
Functionality: the parser does it's job and only parsers the features of type 'gene' in a DataFrame
Style: your stile follows our coding conventions
Documentation: The code has an internal documentation
Testing: you did not test the code but i tried it myself and it works
Other: a quick overview on what was done and where it was done is helpful for the reviewer.
