### ISSUE TITLE
Visualization of TSSs

### ISSUE THREAD

**Issue by mwittep** [Integrative-Transcriptomics/tss-prediction-comparison#4]
## Description
As a user of your tool, I want to visualize the results in order to explore the predictions and use the visualizations when presenting my work.

## Acceptance
- [x] The tool returns visualizations that allow users to get an overview of the data. 
- [x] The tools allows a detailed view of the predictions
- [x] #71

## Definition of Ready
If this issues has been discussed with the team and everybody agrees that it is implementable within one iteration, you can assign the label `ready` to it.

**Comment by habicht12** [comment]
Done
