### ISSUE TITLE
First implementation of app not submitting data

### ISSUE THREAD

**Issue by mwittep** [Integrative-Transcriptomics/tss-prediction-comparison#47]
**Describe the bug**

As mentioned in the meeting, the first implementation did not work on my laptop. 

```
:5000/upload:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_RESET
ProjectForm.jsx:83 Error uploading files: TypeError: Failed to fetch
    at handleSubmit (ProjectForm.jsx:71:30)
    at HTMLUnknownElement.callCallback2 (react-dom_client.js?v=17582b1a:3672:22)
    at Object.invokeGuardedCallbackDev (react-dom_client.js?v=17582b1a:3697:24)
    at invokeGuardedCallback (react-dom_client.js?v=17582b1a:3731:39)
    at invokeGuardedCallbackAndCatchFirstError (react-dom_client.js?v=17582b1a:3734:33)
    at executeDispatch (react-dom_client.js?v=17582b1a:7014:11)
    at processDispatchQueueItemsInOrder (react-dom_client.js?v=17582b1a:7034:15)
    at processDispatchQueue (react-dom_client.js?v=17582b1a:7043:13)
    at dispatchEventsForPlugins (react-dom_client.js?v=17582b1a:7051:11)
    at react-dom_client.js?v=17582b1a:7175:20
```
**To Reproduce**
Follow instructions of Wiki

**Expected behavior**
the data should be sent to the 
**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Brave and Opera

**Additional context**
I think there is a problem with the rerouting of the localhost to the API backend. Not sure why this works for you, but not for me. 

You can check this VITE config for a similar case in one of our tools: 

https://github.com/UniTuebingen-BDVA/ProtEGOnist/blob/main/vite.config.ts

**Comment by mwittep** [comment]
All developers should test and see if this works under their system. If yes, I will check mine.

**Comment by AmelieFl** [comment]
bei mir funktioniert es denk ich 
![image](https://github.com/Integrative-Transcriptomics/tss-prediction-comparison/assets/148360440/77e8dd50-e595-46a9-b82c-9dba166c222c)

**Comment by AronWichtner** [comment]
![image](https://github.com/Integrative-Transcriptomics/tss-prediction-comparison/assets/64489382/069c969e-af9b-4dea-b4ad-7491dd65a64f)

**Comment by mwittep** [comment]
This also work for me, but once I submit the data, I get an error on the client side (See reported error) and reaction from the server. 

---
Mathias Witte Paz
PhD Student
Integrative Transcriptomics
Interfaculty Institute for Bioinformatics and Medical Informatics (IBMI)
Sand 14
72076 Tübingen
+49 (0)7071 – 29-70447

**Comment by AronWichtner** [comment]
This is what i get after uploading the files:
![image](https://github.com/Integrative-Transcriptomics/tss-prediction-comparison/assets/64489382/25155db7-f6fc-4d26-84d7-32ef8cacc44d)

**Comment by mwittep** [comment]
As reviewed by most, apparently it is a problem appearing only in my case. 

To repaired it, I adapted the config of vite and added the api proxy. See #49
