### ISSUE TITLE
Evaluate if the negative strand requires further processing

### ISSUE THREAD

**Issue by mwittep** [Integrative-Transcriptomics/tss-prediction-comparison#48]
**Describe the problem**

Since the genes in the negative strand go from "higher position" to "lower position" and we expect to take the absolute value, it might be that we should take a look at the decrease of the Wiggle file rather than the increase. 

This should be evaluated

**Comment by Julian-Borbeck** [comment]
Investigated on #2 Trained a seperate classifier for the reverse strand
