### ISSUE TITLE
(Tabular) Visualization of predictions

### ISSUE THREAD

**Issue by mwittep** [Integrative-Transcriptomics/tss-prediction-comparison#50]
## Description

Besides comparing the results with the Master Table, we also want to show our results. As previously discussed, we expect the data to be available to the users, for example, in the form of a table. 

## Acceptance

Please describe what is necessary for this ticket to count as resolved. You do not need to repeat the definition-of-done that your team has agreed on generally.

- [x] Receive the predicted data from the backend, as done in #2
- [x] Show the data in the interface.

**Comment by MarkusHenkel** [comment]
Added on branch https://github.com/Integrative-Transcriptomics/tss-prediction-comparison/commits/Visualization
