### ISSUE TITLE
Download predictions from the client side

### ISSUE THREAD

**Issue by mwittep** [Integrative-Transcriptomics/tss-prediction-comparison#51]
## Description

As a user, besides visualizing the predictions and the comparisons in the interface (#31 and #50), I want to be able to get the predictions return by the tool.

- [x] #54
- [x] #55

**Comment by MarkusHenkel** [comment]
Solved in #55. https://github.com/Integrative-Transcriptomics/tss-prediction-comparison/issues/55#issuecomment-2315294558 for specification.
