### ISSUE TITLE
Make the download of the files possible from the interface

### ISSUE THREAD

**Issue by mwittep** [Integrative-Transcriptomics/tss-prediction-comparison#55]
Returns the ZIP provided by the endpoint of the API for the user to download the data.

**Comment by MarkusHenkel** [comment]
Added in commit https://github.com/Integrative-Transcriptomics/tss-prediction-comparison/commit/3b946a2abd9d384cff1c4fcac7248c64255147d2 on branch https://github.com/Integrative-Transcriptomics/tss-prediction-comparison/compare/51-download-predictions-from-the-client-side and then merged into branch dev
