### ISSUE TITLE
Testing on different datasets 

### ISSUE THREAD

**Issue by mwittep** [Integrative-Transcriptomics/tss-prediction-comparison#56]
## Description

All wiggle files are different. Similar with GFF and MasterTables. Hence, it is important that multiple datasets are tested. For this, the PO has provided different datasets (also small subsets) that should cover different studies and hence test different input cases. 

## Acceptance

- [ ] The program has been tested on Pseudomonas aeruginosa dataset
- [x] The classifier has been tested independently.
- [x] The program has been tested on Staphylococcus aureus.
- [x] The classifier has been tested independently.
- [ ]  All bugs have been reported in the repository

**Comment by Julian-Borbeck** [comment]
Implemented in #6f28cd2dc52bca557a4f0813caef6280475575b6
