### ISSUE TITLE
The visualization pages show the correct label of the visualization

### ISSUE THREAD

**Issue by mwittep** [Integrative-Transcriptomics/tss-prediction-comparison#62]
The "View Condition"-button of the Project-Manager leads to the visualization page for the corresponding condition but the page itself doesnt state which condition you are looking at. Currently it only says "This is the visualization content for Condition ID: <conditionID>".

Change the condition ID to the condition name.

**Comment by habicht12** [comment]
Done on 30.08.204

changes are on the dev branch
