### ISSUE TITLE
Runtime analysis

### ISSUE THREAD

**Issue by mwittep** [Integrative-Transcriptomics/tss-prediction-comparison#63]
## Description

As a developer, it would be interesting to learn where the bottlenecks of our backend computation are. For this it would be interesting to learn, what part of the TSS prediction consumes more time (parsing, preprocessing, prediction, post-processing). This can be easily measured in the backend. This can be combined with the testing on different datasets.

## Acceptance

- [ ] Implement the runtime printing in the backend
- [x] Run the analysis for the given datasets
- [x] Summarize the data into an interpretable way

## Definition of Ready

If this issues has been discussed with the team and everybody agrees that it is implementable within one iteration, you can assign the label `ready` to it.

**Comment by Julian-Borbeck** [comment]
solved in #6f28cd2dc52bca557a4f0813caef6280475575b6
