### ISSUE TITLE
[Low Prio] Speed up back-end process

### ISSUE THREAD

**Issue by mwittep** [Integrative-Transcriptomics/tss-prediction-comparison#68]
## Description

Depending on the results of #63 and #65, this issue might be already solved. If #63 states that the runtime bottleneck is on the preprocessing of the files, this can be immediately closed. Otherwise, it might be possible to optimize the runtime of the backend. 

## Acceptance

- [ ] The bottlenecks are identified via #63
- [ ] The specific functions that slow down the process are improved once more

**Comment by MarkusHenkel** [comment]
Moved into Done on Jul 17 (Sprint 6)
