### ISSUE TITLE
Comparing our TSS with TSSpredator's TSS results in 0 common TSS

### ISSUE THREAD

**Issue by AronWichtner** [Integrative-Transcriptomics/tss-prediction-comparison#69]
Comparing our TSS with TSSpredator's TSS results in 0 common TSS.

As discussed in the back end team this might be due to an issue in the prediction.
The latest branch is branch 51.

**Comment by mwittep** [comment]
Just for clarification, only for datasets that were not included in the training, right?
---
Mathias Witte Paz
PhD Student
Integrative Transcriptomics
Interfaculty Institute for Bioinformatics and Medical Informatics (IBMI)
Sand 14
72076 Tübingen
+49 (0)7071 – 29-70447

**Comment by AronWichtner** [comment]
Bug was fixed by @Julian-Borbeck . There was a indexing problem in the prediction
